apiVersion: v1
kind: Pod
metadata:
  name: rbd2
spec:
  containers:
    - image: kubernetes/pause
      name: rbd-rw
      volumeMounts:
      - name: rbdpd
        mountPath: /mnt/rbd
  volumes:
    - name: rbdpd
      rbd:
        monitors:
        - '10.10.113.15:6789'
        - '10.10.113.16:6789'
        - '10.10.113.17:6789'
        pool: kube
        image: foo
        fsType: xfs
        readOnly: false
        user: admin
        secretRef:
          name: ceph-secret
#        imageformat: "2"
#        imagefeatures: "layering"