apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  rbd:
    monitors:
    - '10.10.113.15:6789'
    - '10.10.113.16:6789'
    - '10.10.113.17:6789'
    pool: kube
    image: foo
    fsType: xfs
    readOnly: false
    user: admin
    secretRef:
      name: ceph-secret
#    imageformat: "2"
#    imagefeatures: "layering"